name: Development

on:
  pull_request:
    branches: ['*']

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check Types
        run: npm run type-check
